
amazonProperties:
  endPointUrl: ${AMAZON_S3_ENDPOINT}
  accessKey:  ${AMAZON_ACCESS_KEY}
  secretKey: ${AMAZON_SECRET_KEY}
  testCasesBucketName: ${AMAZON_S3_TEST_CASES_BUCKET}
  region:  ${AMAZON_S3_BUCKET_REGION}